# Introdução à Linguagem Julia

Julia é uma linguagem dinâmica de alto nível e alto desempenho.
Ela se assemelha ao MatLab e ao Python na facilidade de escrita
de código, mas sua velocidade pode ser comparável ao C e Fortran.

# Jupyter

O Jupyter é uma interface web para Julia, Python, e muitas outras.
Ela **não** é o Julia, isto é, o Julia não depende do Jupyter para
funcionar. No entanto, usando o Jupyter, aulas e apresentações
ficam mais práticas.

Cada *célula* do Jupyter pode ser executada com um `ctrl+enter`, ou
um `ctrl+shift`, sendo que o último move a seleção para a célula de
baixo.
Você pode adicionar novas células usando o `+` no topo da página.

# O REPL - Terminal Interativo

Ao abrir o Julia no Windows, ou digitar `julia` no terminal do Mac
ou Linux, se abrirá um prompt tipo

````julia
julia>
````

O Jupyter também serve como esse prompt e todo comando digitado aqui
pode ser digitado lá.

# Básico

In [1]:
2 + 3

5

In [2]:
3 * 5

15

In [3]:
7 ^ 3

343

In [4]:
exp(2)

7.38905609893065

In [5]:
sin(3.14159/4)

0.7071063120935576

In [6]:
pi

π = 3.1415926535897...

In [7]:
sin(pi/4)

0.7071067811865475

In [8]:
round(1.2)

1.0

In [9]:
sqrt(2)

1.4142135623730951

In [10]:
abs(-3)

3

In [11]:
x = 3

3

In [12]:
x ^ 2

9

In [13]:
y = 2x

6

In [14]:
y - x

3

In [15]:
1e-2 # 10⁻²

0.01

In [16]:
1e3 # 10³

1000.0

In [17]:
0.1 + 0.2 - 0.3

5.551115123125783e-17

## Exercício

- Calcule $\varphi = \dfrac{\sqrt{5} + 1}{2}$.

# Álgebra Linear Numérica

In [18]:
rand(3)

3-element Array{Float64,1}:
 0.971408
 0.256517
 0.46544 

In [19]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [20]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [21]:
rand(2,4)

2×4 Array{Float64,2}:
 0.76662   0.583693  0.895153  0.331225
 0.617614  0.773957  0.66608   0.416538

In [22]:
v = rand(3)

3-element Array{Float64,1}:
 0.0675476
 0.691486 
 0.0598507

In [23]:
A = rand(2, 3)

2×3 Array{Float64,2}:
 0.228805  0.862076  0.725537
 0.777625  0.607793  0.321778

In [24]:
A * v

2-element Array{Float64,1}:
 0.654993
 0.492066

In [25]:
w = rand(2)

2-element Array{Float64,1}:
 0.16244 
 0.716995

In [26]:
A' * w

3-element Array{Float64,1}:
 0.59472 
 0.575821
 0.34857 

In [27]:
B = rand(2, 3)

2×3 Array{Float64,2}:
 0.476358  0.125892  0.572003
 0.524707  0.656917  0.3111  

In [28]:
A + B

2×3 Array{Float64,2}:
 0.705163  0.987968  1.29754 
 1.30233   1.26471   0.632878

In [29]:
A * B'

2×2 Array{Float64,2}:
 0.632531  0.912084
 0.631002  0.9074  

In [30]:
A' * B

3×3 Array{Float64,2}:
 0.517018  0.53964   0.372796
 0.72957   0.507798  0.682195
 0.514455  0.302721  0.515115

In [31]:
A = rand(3, 3)
b = rand(3)
x = A\b # Resolve o SL

3-element Array{Float64,1}:
 -0.110189
  0.735067
  5.09448 

In [32]:
A * x - b # É pra ser zero (ou quase)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [33]:
norm(A*x-b) # norm = ‖ ⋅ ‖

0.0

In [34]:
v = [1.0; 2.0; 3.0]
w = [2.0; -2.0; 2.0]
dot(v, w) # ⟨v,w⟩

4.0

In [35]:
det(A)

0.03904466923741308

In [36]:
A^2 # A * A

3×3 Array{Float64,2}:
 0.877564  0.520171  0.0388778
 0.313986  0.532886  0.0521484
 0.773481  0.459843  0.039427 

In [37]:
A .^ 2 # Cada elemento de A ao quadrado

3×3 Array{Float64,2}:
 0.808962   0.106618   0.000330213
 0.0286348  0.459183   0.00411518 
 0.539532   0.0827083  0.00763045 

In [38]:
B = rand(3, 3)

3×3 Array{Float64,2}:
 0.100219  0.0826409  0.911804
 0.112549  0.587617   0.499255
 0.787129  0.627031   0.674903

In [39]:
A .* B

3×3 Array{Float64,2}:
 0.090139   0.0269842  0.0165691
 0.0190453  0.398187   0.032027 
 0.578169   0.180328   0.0589544

## Funções que "distribuem"

In [40]:
exp([0.0; 1.0])

2-element Array{Float64,1}:
 1.0    
 2.71828

In [41]:
sqrt(linspace(0, 1, 10))

10-element Array{Float64,1}:
 0.0     
 0.333333
 0.471405
 0.57735 
 0.666667
 0.745356
 0.816497
 0.881917
 0.942809
 1.0     

## Exercício

- Crie um vetor com os ângulos importantes: 0, pi/6, pi/4, pi/3 e pi/2.
- Crie um vetor com o seno de cada ângulo e outro com o cosseno, usando o vetor acima.
- Calcule a tangente de cada angulo usando os dois vetores acima (tan = sen/cos), mas **sem usar a função tan**.

## Acesso aos elementos

In [42]:
v

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [43]:
v[1]

1.0

In [44]:
v[2]

2.0

In [45]:
A

3×3 Array{Float64,2}:
 0.899423  0.326524  0.0181718
 0.169218  0.67763   0.0641496
 0.734529  0.287591  0.0873524

In [46]:
A[1,1]

0.899423368221111

In [47]:
A[2,3]

0.06414964813323776

In [48]:
v[1:2]

2-element Array{Float64,1}:
 1.0
 2.0

In [49]:
A[:,2]

3-element Array{Float64,1}:
 0.326524
 0.67763 
 0.287591

In [50]:
A[1,:]

3-element Array{Float64,1}:
 0.899423 
 0.326524 
 0.0181718

In [51]:
A[2,3] = 0.0

0.0

In [52]:
A

3×3 Array{Float64,2}:
 0.899423  0.326524  0.0181718
 0.169218  0.67763   0.0      
 0.734529  0.287591  0.0873524

In [53]:
eye(3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [54]:
m, n = size(A)

(3,3)

In [55]:
length(v)

3

## Exercício

- Crie um vetor aleatório e mude o primeiro elemento para o seu oposto (i.e. mude o sinal)

## Matriz por blocos - concatenação

In [56]:
[rand(3,3) zeros(3,2); ones(2,3) eye(2,2)]

5×5 Array{Float64,2}:
 0.317779  0.0846773  0.913177  0.0  0.0
 0.630321  0.128998   0.630151  0.0  0.0
 0.4273    0.0680276  0.146483  0.0  0.0
 1.0       1.0        1.0       1.0  0.0
 1.0       1.0        1.0       0.0  1.0

# Funções

In [57]:
f(x) = x^2
f(2)

4

In [58]:
f(-3)

9

In [59]:
g(a,b) = exp(a + b)

g (generic function with 1 method)

In [60]:
g(2,3)

148.4131591025766

In [61]:
g(3,-3)

1.0

In [62]:
h = x -> sin(x)

(::#1) (generic function with 1 method)

In [63]:
h(2)

0.9092974268256817

In [64]:
function aprox_der(f, a, h)
    (f(a+h) - f(a))/h
end

aprox_der (generic function with 1 method)

In [65]:
aprox_der(h, pi/6, 1e-8)

0.8660254013914681

In [66]:
function aprox_der(f, a, h = 1e-8)
    (f(a+h) - f(a))/h
end

aprox_der (generic function with 2 methods)

In [67]:
aprox_der(h, pi/6)

0.8660254013914681

In [68]:
aprox_der(x->x^2+3x+2, 2) # 2x + 3 com x = 2: 7

6.999999868639861

## Vetor vs Array vs Array 1xN vs Array Nx1

In [69]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [70]:
[1.0 1.0 1.0]

1×3 Array{Float64,2}:
 1.0  1.0  1.0

In [71]:
[1.0; 1.0; 1.0]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [72]:
[1.0, 1.0, 1.0]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [73]:
[1.0 1.0 1.0]'

3×1 Array{Float64,2}:
 1.0
 1.0
 1.0

# Exercícios

- Crie uma função que recebe $a$ e calcula $2\bigg(a + \dfrac{1}{a}\bigg)$.
- Crie uma função que recebe dois catetos e calcula a hipotenusa.
- Crie uma função que recebe uma matriz A e um vetor v e retorna
$\dfrac{\langle v, Av\rangle}{\langle v, v\rangle}$

# Loops e condicionais

In [74]:
for i = 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [75]:
for i = 1:10
    print(i)
end

12345678910

In [76]:
for i = 1:10
    println("i = $i")
end

i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9
i = 10


In [77]:
x = rand(10)
y = zeros(10)
for i = 1:10
    y[i] = x[i] * i
end

In [78]:
x

10-element Array{Float64,1}:
 0.136495 
 0.764157 
 0.0991714
 0.415761 
 0.0439147
 0.505245 
 0.952803 
 0.874854 
 0.417952 
 0.394453 

In [79]:
y

10-element Array{Float64,1}:
 0.136495
 1.52831 
 0.297514
 1.66304 
 0.219573
 3.03147 
 6.66962 
 6.99883 
 3.76157 
 3.94453 

In [80]:
for x in [0; pi/6; pi/4; pi/3; pi/2]
    println("sin($x) = $(sin(x))")
end

sin(0.0) = 0.0
sin(0.5235987755982988) = 0.49999999999999994
sin(0.7853981633974483) = 0.7071067811865475
sin(1.0471975511965976) = 0.8660254037844386
sin(1.5707963267948966) = 1.0


In [81]:
for i = 3:3:20
    print("$i ")
end

3 6 9 12 15 18 

In [82]:
for x in Any["a", 0, 3.14, e, 3//4, im, ones(2), ones(2,2)]
    println("x: $x    Tipo: $(typeof(x))")
end

x: a    Tipo: String
x: 0    Tipo: Int64
x: 3.14    Tipo: Float64
x: e = 2.7182818284590...    Tipo: Irrational{:e}
x: 3//4    Tipo: Rational{Int64}
x: im    Tipo: Complex{Bool}
x: [1.0,1.0]    Tipo: Array{Float64,1}
x: [1.0 1.0; 1.0 1.0]    Tipo: Array{Float64,2}


In [83]:
n = 6
v = ones(n)
v[n/2] = 2
v

LoadError: LoadError: ArgumentError: invalid index: 3.0
while loading In[83], in expression starting on line 3

In [84]:
n/2

3.0

In [85]:
div(n,2)

3

In [86]:
round(Int, n/2)

3

In [87]:
10 % 4

2

# Fatorial
$$ n! = n(n-1)\dots2. 1 $$

In [88]:
function fatorial(n)
    resultado = 1
    for i = 1:n
        resultado = resultado * i
    end
    return resultado
end

fatorial (generic function with 1 method)

In [89]:
fatorial(4)

24

In [90]:
fatorial(5)

120

In [91]:
fatorial(0)

1

## Exercícios

- Faça uma função `soma1(n)` que calcula a soma $1 + 2 + 3 + \dots + n$, usando `for`. (O valor exato é `n(n+1)/2`).
- Faça uma função `soma2(n)` que calcula a soma $1^2 + 2^2 + \dots + n^2$, usando `for`. (O valor exato é `n(n+1)(2n+1)/6`).

In [92]:
function sinal(x)
    if x > 0
        return 1
    elseif x < 0
        return -1
    else
        return 0
    end
end

sinal (generic function with 1 method)

In [93]:
sinal(3.2)

1

In [94]:
sinal(-1.2)

-1

In [95]:
sinal(0.0)

0

In [96]:
function bhaskara(a, b, c)
    Δ = b^2 - 4a*c
    if Δ < 0
        error("Nos reais não tem solução")
    end
    return (-b + sqrt(Δ))/2a, (-b - sqrt(Δ))/2a
end

bhaskara (generic function with 1 method)

In [97]:
bhaskara(1, 5, 6)

(-2.0,-3.0)

In [98]:
bhaskara(1, 0, 1)

LoadError: LoadError: Nos reais não tem solução
while loading In[98], in expression starting on line 1

In [99]:
bhaskara(1, 0, -1)

(1.0,-1.0)

## Exercícios

- Faça uma função `primo(n)` que retorna se o número `n` é primo ou não. Lembrando que `n % p` é o resto da divisão de `n` por `p`.

In [100]:
function ordem(N) # ordem(12) = 1, ordem(500) = 2
    n = 0
    while N > 10
        n = n + 1
        N = N/10
    end
    return n
end

ordem (generic function with 1 method)

In [101]:
ordem(12)

1

In [102]:
ordem(500)

2

In [103]:
ordem(-1) # Não funciona

0

## Exercícios

- Faça uma função `collatz(n)` que calcula uma sequência
$$ a_{n+1} = \left\{\begin{array}{ll}
a_n/2, & \mbox{se $a_n$ é par} \\
3a_n + 1, & \mbox{se $a_n$ é ímpar}.
\end{array}\right.$$
começando de $a_0 = n$, e parando quando $a_n = 1$.
Imprima cada elemento da sequência.

## Operadores lógicos

In [104]:
true

true

In [105]:
true || false

true

In [106]:
true && false

false

In [107]:
if 1 > 0 && "a" in ["a", "b"]
    println("Ok")
end

Ok


In [108]:
function fib(n)
    if (n == 1 || n == 2)
        return 1
    else
        return fib(n-1) + fib(n-2)
    end
end

fib (generic function with 1 method)

In [109]:
fib(1)

1

In [110]:
fib(2)

1

In [111]:
fib(3)

2

In [112]:
fib(5)

5

In [113]:
!true

false

## !(a && b) = !a || !b

In [114]:
x = 0
n = 0

while !(x > 5 || n == 10)
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 4.959916993139618, n = 10


In [115]:
n = 0
x = 0

while x <= 5 && n < 10
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 4.522523440324112, n = 10


In [116]:
## Curto circuito
function imprime_se_positivo(x)
    x > 0 && println("x positivo")
end

imprime_se_positivo (generic function with 1 method)

In [117]:
imprime_se_positivo(1)

x positivo


In [118]:
imprime_se_positivo(0)

false

In [119]:
## Operador ternário
1 > 0 ? "ok" : "nao"

"ok"

In [120]:
maximo(a, b) = a > b ? a : b

maximo (generic function with 1 method)

In [121]:
maximo(2, 3)

3

In [122]:
maximo(5, 3)

5

## Arquivos

In [123]:
;cat exemplo.jl

# Este é um arquivo de exemplo

"""
    y = aprox_log(x)

Retorna um valor aproximado para `log(x)`, utilizando
a expansão

ln(x) = 2(z + z^3/3 + z^5/5 + ...)

onde z = (x-1)/(x+1).
"""
function aprox_log(x)
    y = (x-1)/(x+1)
    return 2*(y + y^3/3 + y^5/5)
end

In [124]:
aprox_log(2)

LoadError: LoadError: UndefVarError: aprox_log not defined
while loading In[124], in expression starting on line 1

In [125]:
include("exemplo.jl")

aprox_log

In [126]:
aprox_log(2)

0.6930041152263374

In [127]:
?aprox_log

search:



```
y = aprox_log(x)
```

Retorna um valor aproximado para `log(x)`, utilizando a expansão

ln(x) = 2(z + z^3/3 + z^5/5 + ...)

onde z = (x-1)/(x+1).


In [128]:
log(2)

0.6931471805599453

## Pacotes

http://pkg.julialang.org/ ou busque no google.

### Instalação de pacotes

In [129]:
# Não rode pois leva um tempo
error("Não rode")
Pkg.add("Plots")
Pkg.clone("https://github.com/abelsiqueira/NLPModels.jl")
Pkg.build("NLPModels.jl")

LoadError: LoadError: Não rode
while loading In[129], in expression starting on line 2

Fazer um pacote dá bastante mais trabalho. Ele exige uma hierarquia
específica do diretório. Só a criação decente de um pacote já seria
uma aula.

Veja http://abelsiqueira.github.io/blog/test-driven-development-in-julia/
e http://abelsiqueira.github.io/blog/automated-testing/
para mais informações, ou o próprio help.

## Plots

In [130]:
using Plots
gr()

Plots.GRBackend()

In [131]:
plot([1; 2; 3], [3; 1; 2])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 
 
 
 
 y1

In [132]:
x = linspace(0, 1, 100)
y = x.^2
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,384.952 36.3154,384.913 42.0271,384.796 47.7388,384.602 53.4505,384.33 59.1622,383.98 64.8739,383.552 70.5856,383.047 76.2974,382.464 82.0091,381.803 
 87.7208,381.064 93.4325,380.248 99.1442,379.354 104.856,378.382 110.568,377.332 116.279,376.205 121.991,375 127.703,373.717 133.414,372.356 139.126,370.918 
 144.838,369.402 150.55,367.808 156.261,366.136 161.973,364.387 167.685,362.56 173.396,360.655 179.108,358.672 184.82,356.612 190.532,354.474 196.243,352.258 
 201.955,349.964 207.667,347.593 213.378,345.144 219.09,342.617 224.802,340.012 230.514,337.33 236.225,334.57 241.937,331.732 247.649,328.816 253.36,325.823 
 259.072,322.752 264.784,319.603 270.496,316.376 276.207,313.072 281.919,309.69 287.631,306.23 293.342,302.692 299.054,299.077 304.766,295.384 310.477,291.613 
 316.189,287.764 321.901,283.838 327.613,279.834 333.324,275.752 339.036,271.592 344.748,267.355 350.459,263.04 356.171,258.647 361.883,254.176 367.595,249.628 
 373.306,245.002 379.018,240.298 384.73,235.516 390.441,230.657 396.153,225.719 401.865,220.705 407.577,215.612 413.288,210.442 419,205.193 424.712,199.868 
 430.423,194.464 436.135,188.982 441.847,183.423 447.559,177.786 453.27,172.072 458.982,166.279 464.694,160.409 470.405,154.461 476.117,148.436 481.829,142.332 
 487.54,136.151 493.252,129.892 498.964,123.556 504.676,117.141 510.387,110.649 516.099,104.079 521.811,97.4316 527.522,90.7062 533.234,83.9031 538.946,77.0222 
 544.658,70.0636 550.369,63.0272 556.081,55.913 561.793,48.7211 567.504,41.4515 573.216,34.1041 578.928,26.6789 584.64,19.176 590.351,11.5954 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [133]:
scatter(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [134]:
scatter(x, rand(100))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [135]:
f(x) = sin(x)
plot(f, 0, 4pi)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 39.4926,194.444 45.1145,170.325 50.7364,146.593 56.3583,123.631 61.9803,101.809 67.6022,81.4769 73.2241,62.9627 78.846,46.5642 84.468,32.5451 90.0899,21.131 
 95.7118,12.5056 101.334,6.80763 106.956,4.12883 112.578,4.51229 118.199,7.95183 123.821,14.3921 129.443,23.7295 135.065,35.8137 140.687,50.4504 146.309,67.404 
 151.931,86.4017 157.553,107.138 163.175,129.279 168.797,152.468 174.419,176.333 180.041,200.49 185.663,224.549 191.284,248.123 196.906,270.834 202.528,292.316 
 208.15,312.223 213.772,330.235 219.394,346.062 225.016,359.449 230.638,370.182 236.26,378.087 241.882,383.037 247.504,384.952 253.126,383.802 258.748,379.605 
 264.37,372.429 269.991,362.389 275.613,349.647 281.235,334.407 286.857,316.916 292.479,297.454 298.101,276.334 303.723,253.897 309.345,230.503 314.967,206.529 
 320.589,182.36 326.211,158.386 331.833,134.992 337.455,112.555 343.076,91.4354 348.698,71.9732 354.32,54.4816 359.942,39.2421 365.564,26.4999 371.186,16.4599 
 376.808,9.28381 382.43,5.08699 388.052,3.93701 393.674,5.85236 399.296,10.8022 404.918,18.707 410.54,29.4394 416.161,42.8268 421.783,58.6538 427.405,76.6657 
 433.027,96.5728 438.649,118.055 444.271,140.766 449.893,164.34 455.515,188.399 461.137,212.556 466.759,236.421 472.381,259.61 478.003,281.751 483.625,302.487 
 489.246,321.485 494.868,338.438 500.49,353.075 506.112,365.159 511.734,374.497 517.356,380.937 522.978,384.377 528.6,384.76 534.222,382.081 539.844,376.383 
 545.466,367.758 551.088,356.344 556.71,342.325 562.331,325.926 567.953,307.412 573.575,287.08 579.197,265.258 584.819,242.296 590.441,218.564 596.063,194.444 
 
 "/>
 
 
 
 
 y1

In [136]:
plot(x->exp(x), -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,384.952 18.7172,383.735 24.6085,382.493 30.4997,381.226 36.391,379.933 42.2823,378.613 48.1736,377.267 54.0649,375.893 59.9562,374.491 65.8475,373.061 
 71.7387,371.601 77.63,370.112 83.5213,368.592 89.4126,367.041 95.3039,365.458 101.195,363.844 107.086,362.196 112.978,360.514 118.869,358.799 124.76,357.048 
 130.652,355.261 136.543,353.439 142.434,351.578 148.325,349.68 154.217,347.744 160.108,345.767 165.999,343.751 171.891,341.693 177.782,339.593 183.673,337.45 
 189.564,335.264 195.456,333.033 201.347,330.756 207.238,328.433 213.13,326.063 219.021,323.644 224.912,321.176 230.803,318.657 236.695,316.087 242.586,313.465 
 248.477,310.789 254.369,308.059 260.26,305.273 266.151,302.429 272.042,299.528 277.934,296.568 283.825,293.547 289.716,290.465 295.608,287.32 301.499,284.11 
 307.39,280.835 313.281,277.494 319.173,274.084 325.064,270.604 330.955,267.054 336.847,263.431 342.738,259.734 348.629,255.961 354.52,252.112 360.412,248.184 
 366.303,244.176 372.194,240.086 378.085,235.913 383.977,231.654 389.868,227.309 395.759,222.875 401.651,218.35 407.542,213.733 413.433,209.022 419.324,204.215 
 425.216,199.309 431.107,194.304 436.998,189.196 442.89,183.984 448.781,178.666 454.672,173.239 460.563,167.702 466.455,162.051 472.346,156.285 478.237,150.402 
 484.129,144.398 490.02,138.272 495.911,132.021 501.802,125.642 507.694,119.133 513.585,112.492 519.476,105.714 525.368,98.7988 531.259,91.7422 537.15,84.5415 
 543.041,77.1939 548.933,69.6963 554.824,62.0457 560.715,54.239 566.607,46.273 572.498,38.1444 578.389,29.8499 584.28,21.3862 590.172,12.7497 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [137]:
plot!(x->exp(-x), -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,384.952 18.7172,383.735 24.6085,382.493 30.4997,381.226 36.391,379.933 42.2823,378.613 48.1736,377.267 54.0649,375.893 59.9562,374.491 65.8475,373.061 
 71.7387,371.601 77.63,370.112 83.5213,368.592 89.4126,367.041 95.3039,365.458 101.195,363.844 107.086,362.196 112.978,360.514 118.869,358.799 124.76,357.048 
 130.652,355.261 136.543,353.439 142.434,351.578 148.325,349.68 154.217,347.744 160.108,345.767 165.999,343.751 171.891,341.693 177.782,339.593 183.673,337.45 
 189.564,335.264 195.456,333.033 201.347,330.756 207.238,328.433 213.13,326.063 219.021,323.644 224.912,321.176 230.803,318.657 236.695,316.087 242.586,313.465 
 248.477,310.789 254.369,308.059 260.26,305.273 266.151,302.429 272.042,299.528 277.934,296.568 283.825,293.547 289.716,290.465 295.608,287.32 301.499,284.11 
 307.39,280.835 313.281,277.494 319.173,274.084 325.064,270.604 330.955,267.054 336.847,263.431 342.738,259.734 348.629,255.961 354.52,252.112 360.412,248.184 
 366.303,244.176 372.194,240.086 378.085,235.913 383.977,231.654 389.868,227.309 395.759,222.875 401.651,218.35 407.542,213.733 413.433,209.022 419.324,204.215 
 425.216,199.309 431.107,194.304 436.998,189.196 442.89,183.984 448.781,178.666 454.672,173.239 460.563,167.702 466.455,162.051 472.346,156.285 478.237,150.402 
 484.129,144.398 490.02,138.272 495.911,132.021 501.802,125.642 507.694,119.133 513.585,112.492 519.476,105.714 525.368,98.7988 531.259,91.7422 537.15,84.5415 
 543.041,77.1939 548.933,69.6963 554.824,62.0457 560.715,54.239 566.607,46.273 572.498,38.1444 578.389,29.8499 584.28,21.3862 590.172,12.7497 596.063,3.93701 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,3.93701 18.7172,12.7497 24.6085,21.3862 30.4997,29.8499 36.391,38.1444 42.2823,46.273 48.1736,54.239 54.0649,62.0457 59.9562,69.6963 65.8475,77.1939 
 71.7387,84.5415 77.63,91.7422 83.5213,98.7988 89.4126,105.714 95.3039,112.492 101.195,119.133 107.086,125.642 112.978,132.021 118.869,138.272 124.76,144.398 
 130.652,150.402 136.543,156.285 142.434,162.051 148.325,167.702 154.217,173.239 160.108,178.666 165.999,183.984 171.891,189.196 177.782,194.304 183.673,199.309 
 189.564,204.215 195.456,209.022 201.347,213.733 207.238,218.35 213.13,222.875 219.021,227.309 224.912,231.654 230.803,235.913 236.695,240.086 242.586,244.176 
 248.477,248.184 254.369,252.112 260.26,255.961 266.151,259.734 272.042,263.431 277.934,267.054 283.825,270.604 289.716,274.084 295.608,277.494 301.499,280.835 
 307.39,284.11 313.281,287.32 319.173,290.465 325.064,293.547 330.955,296.568 336.847,299.528 342.738,302.429 348.629,305.273 354.52,308.059 360.412,310.789 
 366.303,313.465 372.194,316.087 378.085,318.657 383.977,321.176 389.868,323.644 395.759,326.063 401.651,328.433 407.542,330.756 413.433,333.033 419.324,335.264 
 425.216,337.45 431.107,339.593 436.998,341.693 442.89,343.751 448.781,345.767 454.672,347.744 460.563,349.68 466.455,351.578 472.346,353.439 478.237,355.261 
 484.129,357.048 490.02,358.799 495.911,360.514 501.802,362.196 507.694,363.844 513.585,365.458 519.476,367.041 525.368,368.592 531.259,370.112 537.15,371.601 
 543.041,373.061 548.933,374.491 554.824,375.893 560.715,377.267 566.607,378.613 572.498,379.933 578.389,381.226 584.28,382.493 590.172,383.735 596.063,384.952 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [138]:
xlims!(-0.5, 0.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -278.793,384.952 -267.01,383.735 -255.228,382.493 -243.445,381.226 -231.662,379.933 -219.88,378.613 -208.097,377.267 -196.315,375.893 -184.532,374.491 -172.75,373.061 
 -160.967,371.601 -149.184,370.112 -137.402,368.592 -125.619,367.041 -113.837,365.458 -102.054,363.844 -90.2716,362.196 -78.489,360.514 -66.7064,358.799 -54.9239,357.048 
 -43.1413,355.261 -31.3587,353.439 -19.5762,351.578 -7.7936,349.68 3.98897,347.744 15.7715,345.767 27.5541,343.751 39.3367,341.693 51.1192,339.593 62.9018,337.45 
 74.6844,335.264 86.4669,333.033 98.2495,330.756 110.032,328.433 121.815,326.063 133.597,323.644 145.38,321.176 157.162,318.657 168.945,316.087 180.727,313.465 
 192.51,310.789 204.293,308.059 216.075,305.273 227.858,302.429 239.64,299.528 251.423,296.568 263.205,293.547 274.988,290.465 286.771,287.32 298.553,284.11 
 310.336,280.835 322.118,277.494 333.901,274.084 345.683,270.604 357.466,267.054 369.249,263.431 381.031,259.734 392.814,255.961 404.596,252.112 416.379,248.184 
 428.161,244.176 439.944,240.086 451.727,235.913 463.509,231.654 475.292,227.309 487.074,222.875 498.857,218.35 510.639,213.733 522.422,209.022 534.205,204.215 
 545.987,199.309 557.77,194.304 569.552,189.196 581.335,183.984 593.117,178.666 604.9,173.239 616.682,167.702 628.465,162.051 640.248,156.285 652.03,150.402 
 663.813,144.398 675.595,138.272 687.378,132.021 699.16,125.642 710.943,119.133 722.726,112.492 734.508,105.714 746.291,98.7988 758.073,91.7422 769.856,84.5415 
 781.638,77.1939 793.421,69.6963 805.204,62.0457 816.986,54.239 828.769,46.273 840.551,38.1444 852.334,29.8499 864.116,21.3862 875.899,12.7497 887.682,3.93701 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -278.793,3.93701 -267.01,12.7497 -255.228,21.3862 -243.445,29.8499 -231.662,38.1444 -219.88,46.273 -208.097,54.239 -196.315,62.0457 -184.532,69.6963 -172.75,77.1939 
 -160.967,84.5415 -149.184,91.7422 -137.402,98.7988 -125.619,105.714 -113.837,112.492 -102.054,119.133 -90.2716,125.642 -78.489,132.021 -66.7064,138.272 -54.9239,144.398 
 -43.1413,150.402 -31.3587,156.285 -19.5762,162.051 -7.7936,167.702 3.98897,173.239 15.7715,178.666 27.5541,183.984 39.3367,189.196 51.1192,194.304 62.9018,199.309 
 74.6844,204.215 86.4669,209.022 98.2495,213.733 110.032,218.35 121.815,222.875 133.597,227.309 145.38,231.654 157.162,235.913 168.945,240.086 180.727,244.176 
 192.51,248.184 204.293,252.112 216.075,255.961 227.858,259.734 239.64,263.431 251.423,267.054 263.205,270.604 274.988,274.084 286.771,277.494 298.553,280.835 
 310.336,284.11 322.118,287.32 333.901,290.465 345.683,293.547 357.466,296.568 369.249,299.528 381.031,302.429 392.814,305.273 404.596,308.059 416.379,310.789 
 428.161,313.465 439.944,316.087 451.727,318.657 463.509,321.176 475.292,323.644 487.074,326.063 498.857,328.433 510.639,330.756 522.422,333.033 534.205,335.264 
 545.987,337.45 557.77,339.593 569.552,341.693 581.335,343.751 593.117,345.767 604.9,347.744 616.682,349.68 628.465,351.578 640.248,353.439 652.03,355.261 
 663.813,357.048 675.595,358.799 687.378,360.514 699.16,362.196 710.943,363.844 722.726,365.458 734.508,367.041 746.291,368.592 758.073,370.112 769.856,371.601 
 781.638,373.061 793.421,374.491 805.204,375.893 816.986,377.267 828.769,378.613 840.551,379.933 852.334,381.226 864.116,382.493 875.899,383.735 887.682,384.952 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [139]:
ylims!(0.5, 1.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 0.50 
 
 
 0.75 
 
 
 1.00 
 
 
 1.25 
 
 
 1.50 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,435.292 -227.549,432.431 -216.305,429.512 -205.061,426.534 -193.817,423.495 -182.573,420.394 -171.33,417.229 -160.086,414 -148.842,410.705 -137.598,407.343 
 -126.354,403.912 -115.11,400.411 -103.866,396.839 -92.6226,393.194 -81.3788,389.474 -70.1349,385.679 -58.8911,381.806 -47.6473,377.854 -36.4034,373.821 -25.1596,369.706 
 -13.9157,365.507 -2.67186,361.223 8.57198,356.851 19.8158,352.389 31.0597,347.837 42.3035,343.192 53.5474,338.452 64.7912,333.615 76.0351,328.68 87.2789,323.644 
 98.5228,318.505 109.767,313.261 121.01,307.91 132.254,302.45 143.498,296.879 154.742,291.194 165.986,285.393 177.23,279.473 188.474,273.433 199.717,267.269 
 210.961,260.98 222.205,254.562 233.449,248.013 244.693,241.331 255.937,234.512 267.18,227.554 278.424,220.455 289.668,213.21 300.912,205.817 312.156,198.274 
 323.4,190.576 334.644,182.722 345.887,174.707 357.131,166.529 368.375,158.183 379.619,149.668 390.863,140.979 402.107,132.112 413.35,123.064 424.594,113.832 
 435.838,104.411 447.082,94.7986 458.326,84.9895 469.57,74.9803 480.814,64.7668 492.057,54.3449 503.301,43.7102 514.545,32.8586 525.789,21.7855 537.033,10.4864 
 548.277,-1.04327 559.52,-12.8082 570.764,-24.8133 582.008,-37.0633 593.252,-49.5633 604.496,-62.3185 615.74,-75.3339 626.984,-88.6149 638.227,-102.167 649.471,-115.996 
 660.715,-130.106 671.959,-144.505 683.203,-159.198 694.447,-174.19 705.691,-189.489 716.934,-205.1 728.178,-221.029 739.422,-237.283 750.666,-253.869 761.91,-270.794 
 773.154,-288.063 784.397,-305.686 795.641,-323.668 806.885,-342.017 818.129,-360.74 829.373,-379.845 840.617,-399.341 851.861,-419.234 863.104,-439.533 874.348,-460.246 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,-460.246 -227.549,-439.533 -216.305,-419.234 -205.061,-399.341 -193.817,-379.845 -182.573,-360.74 -171.33,-342.017 -160.086,-323.668 -148.842,-305.686 -137.598,-288.063 
 -126.354,-270.794 -115.11,-253.869 -103.866,-237.283 -92.6226,-221.029 -81.3788,-205.1 -70.1349,-189.489 -58.8911,-174.19 -47.6473,-159.198 -36.4034,-144.505 -25.1596,-130.106 
 -13.9157,-115.996 -2.67186,-102.167 8.57198,-88.6149 19.8158,-75.3339 31.0597,-62.3185 42.3035,-49.5633 53.5474,-37.0633 64.7912,-24.8133 76.0351,-12.8082 87.2789,-1.04327 
 98.5228,10.4864 109.767,21.7855 121.01,32.8586 132.254,43.7102 143.498,54.3449 154.742,64.7668 165.986,74.9803 177.23,84.9895 188.474,94.7986 199.717,104.411 
 210.961,113.832 222.205,123.064 233.449,132.112 244.693,140.979 255.937,149.668 267.18,158.183 278.424,166.529 289.668,174.707 300.912,182.722 312.156,190.576 
 323.4,198.274 334.644,205.817 345.887,213.21 357.131,220.455 368.375,227.554 379.619,234.512 390.863,241.331 402.107,248.013 413.35,254.562 424.594,260.98 
 435.838,267.269 447.082,273.433 458.326,279.473 469.57,285.393 480.814,291.194 492.057,296.879 503.301,302.45 514.545,307.91 525.789,313.261 537.033,318.505 
 548.277,323.644 559.52,328.68 570.764,333.615 582.008,338.452 593.252,343.192 604.496,347.837 615.74,352.389 626.984,356.851 638.227,361.223 649.471,365.507 
 660.715,369.706 671.959,373.821 683.203,377.854 694.447,381.806 705.691,385.679 716.934,389.474 728.178,393.194 739.422,396.839 750.666,400.411 761.91,403.912 
 773.154,407.343 784.397,410.705 795.641,414 806.885,417.229 818.129,420.394 829.373,423.495 840.617,426.534 851.861,429.512 863.104,432.431 874.348,435.292 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [140]:
t = linspace(-2, 3, 200)
x = cos(t*pi*2) .* exp(t)
y = sin(t*pi*2) .* exp(t)
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 0 
 
 
 10 
 
 
 20 
 
 
 -10 
 
 
 0 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 248.11,147.763 248.14,147.436 248.109,147.101 248.014,146.766 247.856,146.44 247.634,146.132 247.352,145.85 247.013,145.604 246.624,145.402 246.191,145.251 
 245.725,145.158 245.236,145.128 244.734,145.166 244.234,145.273 243.747,145.451 243.288,145.699 242.869,146.013 242.504,146.39 242.205,146.822 241.983,147.3 
 241.848,147.816 241.809,148.356 241.87,148.909 242.036,149.461 242.308,149.996 242.684,150.501 243.159,150.96 243.726,151.359 244.376,151.685 245.095,151.924 
 245.868,152.068 246.678,152.106 247.505,152.033 248.329,151.844 249.128,151.538 249.88,151.119 250.563,150.59 251.155,149.959 251.636,149.239 251.988,148.443 
 252.195,147.588 252.244,146.694 252.125,145.781 251.834,144.874 251.369,143.995 250.733,143.169 249.933,142.421 248.983,141.774 247.9,141.251 246.704,140.871 
 245.422,140.651 244.082,140.606 242.717,140.746 241.361,141.076 240.05,141.599 238.82,142.309 237.708,143.199 236.749,144.254 235.976,145.455 235.418,146.779 
 235.103,148.196 235.049,149.675 235.272,151.18 235.781,152.674 236.576,154.116 237.653,155.466 238.997,156.684 240.586,157.732 242.393,158.573 244.38,159.175 
 246.506,159.509 248.721,159.554 250.973,159.292 253.204,158.715 255.356,157.822 257.367,156.62 259.177,155.125 260.73,153.36 261.971,151.357 262.852,149.158 
 263.331,146.808 263.375,144.363 262.961,141.88 262.074,139.423 260.715,137.058 258.895,134.851 256.637,132.867 253.979,131.171 250.967,129.822 247.665,128.872 
 244.141,128.367 240.479,128.343 236.765,128.826 233.095,129.829 229.567,131.353 226.28,133.385 223.333,135.897 220.82,138.848 218.83,142.186 217.441,145.841 
 216.721,149.734 216.723,153.777 217.483,157.871 219.023,161.911 221.34,165.79 224.416,169.397 228.207,172.624 232.653,175.367 237.671,177.53 243.158,179.026 
 248.996,179.782 255.049,179.739 261.172,178.857 267.207,177.117 272.991,174.52 278.362,171.089 283.156,166.872 287.219,161.937 290.407,156.377 292.591,150.306 
 293.663,143.855 293.538,137.174 292.156,130.425 289.489,123.782 285.541,117.424 280.349,111.532 273.984,106.283 266.554,101.849 258.196,98.3865 249.082,96.0371 
 239.411,94.9194 229.407,95.1259 219.315,96.7197 209.395,99.7304 199.914,104.152 191.143,109.943 183.348,117.02 176.783,125.267 171.683,134.527 168.258,144.61 
 166.682,155.295 167.093,166.334 169.582,177.456 174.191,188.375 180.909,198.794 189.669,208.416 200.347,216.948 212.762,224.11 226.68,229.644 241.814,233.323 
 257.831,234.953 274.357,234.388 290.987,231.528 307.29,226.33 322.825,218.81 337.145,209.044 349.812,197.172 360.411,183.396 368.558,167.979 373.913,151.238 
 376.192,133.544 375.177,115.309 370.726,96.9841 362.777,79.0423 351.357,61.9729 336.588,46.2674 318.682,32.4067 297.946,20.8484 274.776,12.0134 249.653,6.27306 
 223.133,3.93701 195.838,5.24177 168.441,10.3409 141.655,19.2965 116.21,32.0731 92.8409,48.5337 72.2666,68.4375 55.1688,91.4414 42.1738,117.104 33.8327,144.89 
 30.6037,174.184 32.8345,204.297 40.7483,234.483 54.4309,263.956 73.8218,291.91 98.7081,317.535 128.722,340.041 163.344,358.679 201.904,372.761 243.598,381.685 
 287.498,384.952 332.568,382.184 377.69,373.143 421.687,357.743 463.351,336.057 501.471,308.33 534.868,274.975 562.426,236.574 583.123,193.872 596.063,147.763 
 
 "/>
 
 
 
 
 y1

In [141]:
plot(sin, 0, 2pi, label="sin")
plot!(cos, 0, 2pi, label="cos", c=:green)
plot!(x->1, 0, 2pi, c=:red, l=:dash, label="")
plot!(x->-1, 0, 2pi, c=:red, l=:dash, label="")
ylims!(-1.2, 1.2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,35.6882 97.1342,35.6882 102.936,35.6882 108.737,

In [142]:
xticks!(0:pi/2:2pi)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0000000 
 
 
 1.5707963 
 
 
 3.1415927 
 
 
 4.7123890 
 
 
 6.2831853 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3

In [143]:
xticks!(0:pi/2:2pi, ["0", "\\pi /2", "\\pi", "3\\pi/2", "2\\pi"])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 π 
 
 
 /2 
 
 
 π 
 
 
 3 
 
 
 π 
 
 
 2 
 
 
 
 2 
 
 
 π 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,3

In [144]:
x = linspace(0, 2*pi, 100)
anim = Animation()
for i = 1:5:100
    plot(x[1:i], sin(x[1:i]))
    frame(anim)
end
gif(anim, "exemplo.gif", fps=10)

INFO: Saved animation to /home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo.gif


Plots.AnimatedGif("/home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo.gif")

In [145]:
x = linspace(0, 2*pi, 100)
anim = Animation()
for i = 1:3:100
    plot(x[1:i], sin(x[1:i]))
    xlims!(x[1], x[end])
    ylims!(-1, 1)
    frame(anim)
end
gif(anim, "exemplo2.gif", fps=12)

INFO: Saved animation to /home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo2.gif


Plots.AnimatedGif("/home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo2.gif")

In [146]:
x = linspace(0, 2*pi, 100)
anim = Animation()
for i = 1:3:100
    plot(x, sin(x), leg=false)
    a = x[i]
    scatter!([a], [sin(a)], c=:red)
    plot!(x, sin(a) + cos(a)*(x-a), c=:red, l=:dash)
    xlims!(x[1], x[end])
    ylims!(-2, 2)
    frame(anim)
end
gif(anim, "exemplo3.gif", fps=12)

INFO: Saved animation to /home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo3.gif


Plots.AnimatedGif("/home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo3.gif")

In [147]:
t = linspace(0, 5, 100)
x = cos(pi*t) .* t
y = sin(pi*t) .* t
z = sqrt(t)
plot(x, y, z, m=(3,:red), c=:blue)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 39.4926,279.187 48.0576,282.18 44.3482,284.375 48.0576,282.18 79.7522,293.257 72.3334,297.646 79.7522,293.257 111.447,304.334 107.737,306.528 111.447,304.334 
 143.141,315.411 135.723,319.799 143.141,315.411 174.836,326.487 171.127,328.682 174.836,326.487 206.531,337.564 199.112,341.953 206.531,337.564 238.225,348.641 
 234.516,350.835 238.225,348.641 269.92,359.718 262.501,364.106 269.92,359.718 301.615,370.794 297.905,372.989 301.615,370.794 333.309,381.871 325.89,386.26 
 333.309,381.871 342.125,384.952 
 "/>
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 342.125,384.952 364.666,371.618 367.693,372.675 364.666,371.618 394.564,353.932 400.617,356.047 394.564,353.932 424.462,336.246 427.488,337.304 424.462,336.246 
 454.36,318.56 460.412,320.675 454.36,318.56 484.258,300.874 487.284,301.932 484.258,300.874 514.156,283.188 520.208,285.304 514.156,283.188 544.053,265.502 
 547.08,266.56 544.053,265.502 573.951,247.817 580.004,249.932 573.951,247.817 596.063,234.737 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 318.766,250.333 320.585,241.378 322.75,237.592 325.11,234.374 327.503,231.284 329.761,228.168 331.717,224.971 333.212,221.688 334.103,218.346 334.268,214.993 
 333.61,211.694 332.066,208.523 329.607,205.562 326.241,202.892 322.016,200.593 317.019,198.738 311.37,197.39 305.228,196.601 298.777,196.403 292.229,196.813 
 285.809,197.829 279.757,199.425 274.312,201.556 269.708,204.158 266.166,207.145 263.882,210.415 263.026,213.852 263.726,217.326 266.071,220.702 270.101,223.839 
 275.802,226.596 283.112,228.838 291.909,230.438 302.024,231.285 313.237,231.282 325.281,230.358 337.855,228.461 350.625,225.572 363.234,221.696 375.314,216.87 
 386.497,211.16 396.423,204.663 404.752,197.501 411.175,189.822 415.427,181.796 417.291,173.609 416.609,165.46 413.292,157.556 407.317,150.105 398.739,143.31 
 387.685,137.364 374.358,132.446 359.03,128.71 342.04,126.285 323.783,125.268 304.706,125.721 285.292,127.667 266.049,131.091 247.499,135.937 230.163,142.105 
 214.545,149.461 201.117,157.831 190.311,167.01 182.498,176.763 177.979,186.835 176.98,196.952 179.634,206.833 185.983,216.193 195.97,224.756 209.439,232.255 
 226.137,238.448 245.718,243.12 267.749,246.089 291.72,247.215 317.056,246.404 343.13,243.609 369.279,238.837 394.823,232.144 419.077,223.643 441.376,213.494 
 461.087,201.905 477.632,189.129 490.502,175.456 499.27,161.205 503.61,146.72 503.303,132.358 498.246,118.482 488.459,105.45 474.088,93.6066 455.399,83.2727 
 432.779,74.7373 406.727,68.2489 377.84,64.0079 346.804,62.1604 314.375,62.7934 281.361,65.9309 248.602,71.5326 216.95,79.4929 187.245,89.6431 160.293,101.754 
 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [148]:
x = linspace(-2, 2, 100)
y = copy(x)
f(x,y) = exp(-(x^2 + y^2))
contour(x, y, f)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#f3e258; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 305.074,211.763 302.268,213.842 299.276,215.612 297.073,216.704 291.877,218.627 288.478,219.461 286.682,219.844 281.487,220.398 276.291,220.398 271.096,219.844 
 269.3,219.461 265.9,218.627 260.705,216.704 258.502,215.612 255.509,213.842 252.704,211.763 250.314,209.547 248.84,207.915 246.244,204.066 245.119,201.548 
 244.601,200.217 243.853,196.369 243.853,192.52 244.601,188.671 245.119,187.341 246.244,184.823 248.84,180.974 250.314,179.342 252.704,177.126 255.509,175.047 
 258.502,173.277 260.705,172.185 265.9,170.262 269.3,169.428 271.096,169.045 276.291,168.491 281.487,168.491 286.682,169.045 288.478,169.428 291.877,170.262 
 297.073,172.185 299.276,173.277 302.268,175.047 305.074,177.126 307.464,179.342 308.937,180.974 311.534,184.823 312.659,187.341 313.177,188.671 313.924,192.52 
 313.924,196.369 313.177,200.217 312.659,201.548 311.534,204.066 308.937,207.915 307.464,209.547 305.074,211.763 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#fabf26; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 316.527,219.461 312.659,222.326 311.108,223.309 307.464,225.341 303.519,227.158 302.268,227.676 297.073,229.394 291.877,230.667 289.794,231.006 286.682,231.474 
 281.487,231.863 276.291,231.863 271.096,231.474 267.984,231.006 265.9,230.667 260.705,229.394 255.509,227.676 254.259,227.158 250.314,225.341 246.67,223.309 
 245.119,222.326 241.25,219.461 239.923,218.312 237.181,215.612 234.728,212.69 234.028,211.763 231.709,207.915 229.99,204.066 229.532,202.523 228.902,200.217 
 228.377,196.369 228.377,192.52 228.902,188.671 229.532,186.366 229.99,184.823 231.709,180.974 234.028,177.126 234.728,176.199 237.181,173.277 239.923,170.577 
 241.25,169.428 245.119,166.563 246.67,165.58 250.314,163.548 254.259,161.731 255.509,161.213 260.705,159.495 265.9,158.222 267.984,157.882 271.096,157.415 
 276.291,157.026 281.487,157.026 286.682,157.415 289.794,157.882 291.877,158.222 297.073,159.495 302.268,161.213 303.519,161.731 307.464,163.548 311.108,165.58 
 312.659,166.563 316.527,169.428 317.855,170.577 320.597,173.277 323.05,176.199 323.75,177.126 326.068,180.974 327.788,184.823 328.246,186.366 328.876,188.671 
 329.401,192.52 329.401,196.369 328.876,200.217 328.246,202.523 327.788,204.066 326.068,207.915 323.75,211.763 323.05,212.69 320.597,215.612 317.855,218.312 
 316.527,219.461 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#fb9c07; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 324.122,227.158 323.05,227.952 318.404,231.006 317.855,231.333 312.659,234.033 310.797,234.855 307.464,236.213 302.268,237.957 299.465,238.704 297.073,239.302 
 291.877,240.273 286.682,240.914 281.487,241.234 276.291,241.234 271.096,240.914 265.9,240.273 260.705,239.302 258.313,238.704 255.509,237.957 250.314,236.213 
 246.981,234.855 245.119,234.033 239.923,231.333 239.374,231.006 234.728,227.952 233.656,227.158 229.532,223.716 229.092,223.309 225.447,219.461 224.337,218.081 
 222.504,215.612 220.149,211.763 219.141,209.687 218.333,207.915 217.023,204.066 216.157,200.217 215.726,196.369 215.726,192.52 216.157,188.671 217.023,184.823 
 218.333,180.974 219.141,179.202 220.149,177.126 222.504,173.277 224.337,170.808 225.447,169.428 229.092,165.58 229.532,165.173 233.656,161.731 234.728,160.937 
 239.374,157.882 239.923,157.556 245.119,154.856 246.981,154.034 250.314,152.676 255.509,150.932 258.313,150.185 260.705,149.587 265.9,148.616 271.096,147.974 
 276.291,147.655 281.487,147.655 286.682,147.974 291.877,148.616 297.073,149.587 299.465,150.185 302.268,150.932 307.464,152.676 310.797,154.034 312.659,154.856 
 317.855,157.556 318.404,157.882 323.05,160.937 324.122,161.731 328.246,165.173 328.686,165.58 332.331,169.428 3

In [149]:
contour(x, y, f, fill=true)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nOy97ZbroK4sKkivPc55
/4e9Z+zVgfvDFhSiwDhOutMzqjnGdIwxdtKJ9VWSgsgti+OHEX/7BpYQfuI+w+99Fj/y/ob4G9+B
90H6tSvnX7y25J+59q++x2X8hXv8m/CnkcPhcDgcHwxXBBwOh8Ph+GC4IuBwOBwOxwcjOEfg1Xgv
XevH4uIviP3/zL3/ImfhF/kS74T8Q3Fxjtdf+yXx+I/lErzb/fxN+JPH4XA4HI4PhisCDofD4XB8
MFwRcDgcDofjg+EcgafiA3LinxzHfs19v4Cf8CPxe9fLN/xQvPvpcfXn3/fTY/IfwSVw3sBZ+JPH
4XA4HI4PhisCDofD4XB8MFwRcDgcDofjg+EcgSX847H/i/Hvd4vzvyae/xN/h/D6a/wF5J96JD03
lnydc/Dk+7m63j/PJ3AugeLrt2/A4fhIuNAfg302P6YcOByfBw8NOBwOh8PxwXBFwOFwOByOD4Zz
BDr8jm70kjj728X+19e7Fud/xWf5XFf+j9V9+Efwmvr8z370XbvHdY7Bm9UreAGXwOsQ/CycI+Bw
IF4Qu3ehfx3sM7wsLJyL4HCIiIcGHA6Hw+H4aLgi4HA4HA7HB+ODOQJ/uDbAr9b7/838/sXzL7j3
X+HGD+H29DUdIjnfn7/mpVj56qP0p7gE1679bn0OnDfwOjhHwOF4Il4h9P9ljsGVhzv7rF+hHDgc
/zr+3SeMw+FwOByOQ3xIaOBn9J13SwG8fj9r56+7/K+GRNZc/lfe91WL/jWhhX9XX392K+Cr7uMr
HoXla1/OTFi7zrnP9vHP7d1KGf9cCOHfCRf8u08Yh8PhcDgch3COgOM98QO1+M9Y/9e8DC/wEsjf
IiBm4Zb2lc+GWbxn/k7McvwR3sHou+01DBy/BPcIOBwOh8PxwfgHPQJ/lA/wY+WAX1Hm9/lpfT8R
5z9zjSuW6yus9z/HG3iFsXvVabR6T6vXufgec1jlGKxyd05ce/ne17wwp+L07Lt8gTfwkiqUFOzv
8Dd5A3/saeJwOBwOh+OZ+Ac9Ao5PwrOt/zOW9hVL/zW8gffQ63ns/dq9cT7A2ud/hp+wyjv4NX6B
w/ECvMeTw+FwOBwOx6/gj3sE/gAf4A1j/901hvf43Nj/uZj871j6Z6z8a7yBf7jewLvxAc7cz7P5
AGfue3HNZ3MJREaNGNl1Vn9H66Dx+9Xv8iKXwHkDc/xxRcDxSfgJoX8uNOAphRSvyPy8olxcFMYs
tPDssILD8Zt4ExPC4XA4HA7Hb8A9Ag7HH8TbWP8E7N5GhD2Hw/H7+EOKwL/NB3hFK+DLdQCeHPu/
Wsnv2XF+tt5fqS3wNnyAVVzlDfwmR+Cn6g08mZ+wzCUQoXyC1ToE61wCfj+XwicXahCMfuvPD928
P2/gDykCjn8Rox/jT8T5rygbo2svn/tjJNI3wU8V/7l6bXadCwJ6lV8wPv+9BIbj34QrAg7Hi/Fx
Qp/gqvW1Ss5zOBzn8fefMA6Hw+FwOB7Gm3oEXq+fXLay/gQf4FodgGfH/s+44n8izs/PfX4dgavf
tfjX+AAnkH7C5f+bHIFXXPsF75vyCS70NDhXg+DJaZcXexf8TMrn+mfxE3hTRcDx13E1/k7XXBT6
71ZH4Kogf+cMgauIF7gDy0rEL3IE2LlnQhr0++hcAseT4YqAw/FErAr9y1kDfyyqNxJUV/oFsM86
OW/A4TiNv/U0cTgcDofD8VT8skfgD9QGEFnmA7yiL8ClWgAX6wA8O/Z/Nf7+7OtcrSPALNLla1/8
Tn5cHYFFsFDDKR7CT3AERj/Ln7rO4rWv9DRYrUEgIpIX3/d6hGaxd8Hb8QZEfqvmgIcGHKfw7Nj/
mCz4uNC/QuI7E8+n135Bu2N+7T+mCPxiHYEzPASqNDyZI3CmoNAqn8C5BI4rcEXA8RG4bIH/gNC/
6o14Z5yxypmwutLkZ3ydtbLH3jjI8a/jBxUBDwNM1zv1YF8LA1xN//tNV/wV6/+KpT96L9eyE56f
XfDXPAKXrXKGF6TRrd7nsufgamjgp9IZL1xnPfVwQBhdLha1tuay4jas8Ph5rY3/1tPE4XA4HA7H
U+GhAcdLcDXn/9nW/1US3xVi4bo34mf6HLw7LlnlDFfJeQTLpMRXWOUXaxM4HBauCDg+FucUk8eF
/nKI5oRwj3/MmfcShykVxid4A4uC1/kAjn8dL1IE/gAf4CXx2B8oB7wt0A9RofYKK/hxS/0Mv+DZ
1v/6/fDP4opVvyrgzwj3v+YROPNLvSJ2X5IhsOg5uOQlGF3nCu/gFddePPdKyWIRnn74I7wBkUup
hn+VN+AegQ/DT7nnr6b6/ZbQHwn8K1b9qoB3j8CG1Xd29fH6Evf+o9c4c51nzzsx170j/yb+1tPE
4XA4HA7HU+EeAcc/A2u1oxdg3cOw7h25Yumfsehf4VF4JWhfgMF7SNTC7OeyeYMgzuI1OB7xEjhR
z/HX8WcUAecDwNAiH+Cn4vTP5hKIPBYGsOvjsVWhP/osmCC7Evt/BR/gXcIFrwgDXLnO6BrL5x8p
B3r8QrigW9OujXi3GgarYYVRyWJaY5g9Z9ipz+UNiDy/RPFfKEj1ZxQBx/uhF7y34bHt+JmY/HnF
xh6PBx6BM5b6Fav+ihJx7jrv4RE4g6vC/Mo1rtCtUJgXAX6l+I885o0YXWe1aqLDIeIcAYfD4XA4
PhruEXC8FRqvwiTmP5ojMvcE4PpnLPVV9/6q5+CM9b5cw+BN9PpTPRMWbfBEP+v+3DOW8CNOZcp/
2L9vj1vv7+UmdnwenqAIPP/h8xN8gHPXeDIf4ESPzp/gAzzaAdCu9Rg5z6yxGPOfrzm+xzg5Zo8f
jV8R+ueE5d9SBM7g2aGBVeH+6Pmz+33YtT8JH1xa84eqGl5NXXx2u+MrvAGREzH9J/MGhtdZxuPB
LvcIfBBGMfxHCwqdJ+cdC8TVmP9ojr2OFY5HHoGrHIFVof+KrIGYr/b6fRJe0BnxioA/wxE4Oj+S
sRmWBPkTyIZ0zSeSBT0z4t+GKwKOX8MjjP+Zq7/MX/QIrFj57fyx92K2Jh07IbT/XGjghNCIi+Xr
ElEuWFog/5u089Lu3n9EudBzHrW9aItlXc0Fr+OX8B5PDofD4XA4HL+Ckx6BN9MbXuCC/C0+wNg9
/zw+wMjt/miJ4Xm63vPCAKsxfzbHHj/LEYgT8uIV6985AhuWXezMQl78/dszZ2ddiS4vz1upI3Ax
XJCezRGY3c8LahjwmDwjBDybNyByqXj1Bd7Aa7D2rfTQwB/CXJBeK+DTznmMBzBj/J9fi7+3Wcyf
zTnPERi7/2dKRRlbFPpXiwzFxQYuq673R5HIU5y9jzQghNG55EFFH+MPKgcz9/5s/tE5K6JmlWx4
tTZBDGukwtUQBAtfTO/nwes4fgeuCDhejqsKwKMx/7lngCstK1kDVtgfnc8VhjMegWtepVeCJUEy
ay5mni55RZGgHAEjcLKkTjnQ9Y84BpzBHfd5CeaNUxaZN8KOraYkepqh41WYKAKvf6j81IOLX2f9
2j8RBhi1DJ4T6s5X8rsSQhCZu/9H93qm4h8T3o+6+leJfkcEQpFW+M9CBKtCnwn3c+GCte/ab3gE
mHrA560rErSF7cJbSzLwHIgceg9WPQdnPAyJzHuVl

In [150]:
contour(x, y, f, fill=true, c=:gray)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nO1d24KzrA4Fv//9n3iP
7IsWCGElBA+t1qyLmRZDQKvmSIghhBQcji8hxvjtKTgcl0VK/np2nI/l2xNwOBwOh8PxPbgi4HA4
HA7Hg+GKgMPhcDgcD0YMniPgOAEe+5+HX7MXPC4+D79mjj1wj4DD4XA4HA+GKwIOh8PhcDwYrgg4
HA6Hw/FgeI6AYwpPjWM/9bx/GU+Mqz/xnB1juEfA4XA4HI4HwxUBh8PhcDgeDFcEHA6Hw+F4MDxH
wPFz8e9fOx/HPfBr8fdfOx+HDPcIOBwOh8PxYLgi4HA4HA7Hg+GKgMPhcDgcD4bnCPww7hwrv/Pc
Lfj18zsaT4hX3/Uc7zpvR8V/356Aw/HrcKG/H+gaugByOI6BhwYcDofD4XgwXBFwOBwOh+PB8ByB
G+KuruY7zPuMOd7hvO+IM0IDdwg33GGOCHed9xPgOQIOx4FwRWIOe4SD5w04HMfAQwMOh8PhcDwY
7hG4OO5gDV5tjnvms/dc3CPwXHzKG2G9H67mHZHmfbV5PhHuEXA4HA6H48Fwj4DjsZixtL/pZYA8
D+d4LiSbb8+1QZbkDD9rf7dYHb8O9wg4HA6Hw/FguEfgIrhiHPibc/qEBf4xj8DmngrPC94vKs6w
qu92DQY42vOw1zvyKbgX5vtwj4DD4XA4HA+GewQct8bR1v+Ul8BMuW+cCabH89yCnbF7zBLwtPYV
2q2W6NF0DsfV4B4Bh8PhcDgeDPcInIw7xHI/NcczYvKH05mo5ngKnbf3FVle4147wwbedWYzVvlF
rqGGM7wMV/Nm3LVWwl3hioDjNviE0J8SpldbUngDIbYVe173U1cFCBY0tocLHL8EDw04HA6Hw/Fg
uEfA4bghrmz9uxXscNwLrggciKu9nK8W+9+bI3B0nB/yu0m1wavda1fGjAoCr6pVibnYb7JX+bpD
nN6VzmPgioDjq5BeNh+J8+9QNmZpj+x7RH8HBswHMHfenl8gs3Sh5jgfrgg4HCfDhf7+nefc8nM4
zoMnCzocDofD8WC4R2AjrmalfXM52h46MTRg4rgvzr8nD2GG1j0C94bV77ArvyCEr+YY7PGuXM1b
c7X53AGuCDhOwV4ha+W5J87vioDjSFjzC2aE0h0S9hz3hysCDseBcOUAQxJUewSdW34OxzHwHAGH
w+FwOB4M9wgY8E3r6xNj717CZ3Sx767jbx3ni6EB9wg4KKaWI16sXsHReQNnjGOFe490uCLgmMLR
sX+x7w6h74qA48oQt0VGtDuWV8KxXfg5AFwRcDwCZwjeb+2QOEt7N+zJBzjDEnVr0vHrcEWA4Vsv
2Csu/zva5T+z1G+P9X+G0L6cImCmvAh+WHE5CuYwwg+FEEL4nqK1t8jVL8GTBR0Oh8PheDDcI+A4
BXvX/D/SI2CimuN5GdyksM7VcEZtAoeDwxUBx2MxVelwTwLijvkcQXs77HB9780bwNNxIev4bTxW
Efi1JYEfs4Kt/Xda6p/wCJyiCOzp64rAHJCAfsB12ZVL4HkDlx77W3isIvBU7K33f7TQv40iAFsB
3YeWFLoiIOChIYjdiYa+/PDR8GRBh8PhcDgeDPcIOH4G3Eqm3/cuhbxa4aI9dGdjJk5/9B4CU30P
cp27ley4Ox6hCDw1H+AM4Xd0GODI0MC0ImAcd2Y+R/fdO45jEj+Ud7C7vPHB5+15A9fFIxQBxzk4
xAL/lCKwY4xZ2iP77h3HcQBuqBz8kpBynA/PEXA4HA6H48Fwj4DjUrBa+NY2fnSL12Lr2FvGsY69
h+5szFijVlpEZ207El6nwPGL+DlFwPMBBm3GMd4HVNozQgOHKAIb+UttU2O7IvAM3DBcEMLczoef
Osejtzv2vIF5/Jwi4JAhCsiNwu8SikDXcvwcZ2hdEXgwbqochDBOLLyrgHPY4IqA42vYIrA1V/8e
vlvoXRHAuFpogLd9VKjxsQHJL1mWjnvCkwUdDofD4Xgwbu0R+KV8gFNc0hrNwDK2jPMpa9sa8//m
HI9ok3A3j4BDQUq3DBeUGXvewGXH3oNbKwJPg1VYSvTvxqlxNgvvvUJ2w5gfn6PnDeyuDHjXF+cu
7Kz3fyTM1/o9t61JhT//m94crgg4TsdeBeAMxUTMQTB4R85IktRwFaFvHfNTJYa35gNk/qP+1r57
hdzRZZYdjlm4ImDAJ8IAmwTQqP9GoXS2cLUm/z1NEZi6zy6iHJiFvnsExrjBqoPNuxwecB53DRfc
AZ4s6HA4HA7Hg+EegYvC6gk4gufHPQJCH6nfV+d6Un6C1Vsj4Srhgj3L/xTiriludMXHGL+7fHAv
6Fy/6B3YvWFQCJ43cGG4IuAwYY+wtLj/tWOjNo2nRPfJ0MDWEI2GqygCn0KTwZ5/ww/lCGzJG5Bo
dyHzI7+pJ2E6jsBtFIFPvdC+lQ+wNY5OGud4HiCMTbxm6S+mCMx6BMJGXiI/AVdRBM7wCJgFNOiL
npVbewQQLuIlyPilvIG9PK3jXO0e9BwBh8PhcDgejNt4BH4Zu/IBPhQXN9N304u/5xHYaenPhiUQ
rKTnewSsdPZ5bHXFo7aU0uacmlsAhAu+ian8jfJhHOpwnAtXBByb8Y0wgKYIWNu0eXWCczI0sCeX
QHqXXyUMYB0TC2/cH7/4++u0dd0+Cg1k4TnKMdByBI6sI4Awvd2xYU8Dh0PCJRWBT7zQzhjjG/kA
ewWvlQ62gbneXRGwWPt7Y//tcGOPQJ9uifENRQAhTYihFK1FfXTlAPWVaOo8e1zjCh6AL5cynrq2
B+c87F7h8IGY/qfyE6y4pCLwyxCFsa2zjdcJ7nA01xnBu2mcDykC4YCxGSvxeEcPBNyov4TLKAJ7
EwOJGMmKAhb6iF9k35OoHIwSEK9xNXfghOS8lv2+CpIIpTfh4+GC8+HJgg6Hw+FwPBjuEXg4rBb7
EWNI//e25e+WNs36l/iOx9bpy/eB9T/jEbiKl+DsOvn5mjVeAjX0wI/NXScYliBtUfMmAM+DtW3E
E/U7Ap9wgzuuj68qAldxZW7B0fkA4rWYFFIanVXIWuc6K4y/oQhI4ZRtY4euraNRhP1sLoHafhFF
wLpsACXmvbqP4/y8rbrxAV1EgpfzUoT+AH3Gwo1wwbyBEIRrebG8gU/hW4qZewROglWoKgxsvDbG
xU2KwGDMyyoChGb7tVDOO2Ce2ufRsWbQrhkpDZDU1PdI7F4+OCgnXMnGFjhqSyFB5YAPrSkHI0v9
VkqB9IMddJ+cUemw9CQ87iLY7wLPEXA4HA6H48Fwj4CjwygMYLHK406rHPHSxg4Db4Rt7AFdmAxL
gM98IOSF4IAeAWCHfiXUBoaEljpYJviiRW295YfuSbNr35Q2sM3pHyOpU8DmEAc5AlvrIWzpL8Et
a0cID1EE9r4grfHcLW520mjndVZoQOF/NUUAXa+5sQfzAUJ/JiQiCXtpbDomhzWM8BVFAMHo7g9h
HOevMhZqHB3/qeS8wTJFNPaMME5hVq34Ig6OyU8NDdqwrva9vIE9oY074BGKwOVxsNCfErxWuoso
AgHQaeNwwb9H6M95I/rz5eNJ58aBlU5AdxGxg2W2MLeB0pCFNS48BPgbrXL6v2lTlIPX//4e05SD
bWsYvow8/wMVgrNXlzj2wRUBh4hZ9/wWRQDRc7qg0

In [151]:
surface(x, y, f)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#00002d; stroke-width:1; stroke-opacity:1; fill:none" points="
 6.68429,178.161 5.60444,178.164 5.24449,178.851 5.24449,179.674 5.60444,180.633 6.32434,181.317 7.76414,182.273 8.84399,183.092 9.56389,184.188 9.92384,185.146 
 9.92384,186.381 9.56389,187.068 9.20394,187.343 8.12409,187.346 6.68429,186.801 5.60444,185.982 5.24449,185.434 4.88453,184.475 4.88453,183.241 5.24449,182.554 
 5.96439,182.003 7.04424,182 8.48404,182.133 9.20394,181.994 9.56389,181.308 9.56389,180.485 9.20394,179.526 8.12409,178.706 6.68429,178.161 
 "/>
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 15.3788,283.243 21.7148,279.187 21.7148,266.684 18.5468,268.711 21.7148,266.684 21.7148,254.18 15.3788,258.236 21.7148,254.18 
 21.7148,241.677 18.5468,243.704 21.7148,241.677 21.7148,229.173 15.3788,233.229 21.7148,229.173 21.7148,216.67 18.5468,218.697 21.7148,216.67 21.7148,204.166 
 15.3788,208.222 21.7148,204.166 21.7148,191.663 18.5468,193.691 21.7148,191.663 21.7148,179.159 15.3788,183.215 21.7148,179.159 21.7148,166.656 18.5468,168.684 
 21.7148,166.656 21.7148,154.152 15.3788,158.208 21.7148,154.152 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 15.3788,283.243 21.7148,279.187 56.674,292.408 53.5061,294.436 56.674,292.408 91.6333,305.628 85.2973,309.684 91.6333,305.628 
 126.593,318.849 123.425,320.877 126.593,318.849 161.552,332.069 155.216,336.125 161.552,332.069 196.511,345.29 193.343,347.318 196.511,345.29 231.47,358.511 
 225.134,362.566 231.47,358.511 266.429,371.731 263.261,373.759 266.429,371.731 301.389,384.952 295.053,389.008 301.389,384.952 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 301.389,384.952 301.389,384.952 306.982,387.067 301.389,384.952 330.723,366.175 333.52,367.233 330.723,366.175 360.057,347.398 365.651,349.513 360.057,347.398 
 389.392,328.621 392.188,329.679 389.392,328.621 418.726,309.844 424.319,311.96 418.726,309.844 448.06,291.067 450.857,292.125 448.06,291.067 477.394,272.29 
 482.988,274.406 477.394,272.29 506.729,253.514 509.525,254.571 506.729,253.514 536.063,234.737 541.656,236.852 536.063,234.737 
 "/>
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nOy9fcguW3sf9LvWzH0/
z977nDfJmw+TkKTUNkRq+pFgTCRE/xDUgLSgbUIpWFRaQaXoP7EgYk0VIVSFoFT8QEStNBahIFRB
KtTQVImJxIjYikmNtkls+5r3fc/ZH899r8s/1vW5Zu5nP3vvc87e+9zXb/Pse2bNmjUza2bW77eu
61priJlRKBQKhULhOtHe9gkUCoVCoVB4eyghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQK
hUKhcMUoIVAoFAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAo
FApXjBIChUKhUChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKh
cMUoIVAoFAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApX
jBIChUKhUChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUo
IVAoFAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIC
hUKhUChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAo
FAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKh
UChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAoFAqF
whWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKhUChc
MUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAoFAqFwhWj
hEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKhUChcMUoI
FAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAoFAqFwhWjhECh
UCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKhUChcMUoIFAqF
QqFwxSghUC

In [152]:
n = 100
U = zeros(n, n)
for i = 1:n
    for j = 1:n
        U[i,j] = f(x[i], y[j])
    end
end
V = U[:]
α = 0.1
A = spdiagm( (α*ones(n-1), (1 - 4α)*ones(n), α*ones(n-1)), (-1,0,1))
B = α*speye(n)
Vp = zeros(n*n)

p1 = surface(x, y, U)

M = 2000
for k = 1:M
    I = 1:n
    Vp[I] = A*V[I] + B*V[I+n]
    for i = 2:n-1
        I = (1:n) + (i-1)*n
        Vp[I] = B*V[I-n] + A*V[I] + B*V[I+n]
    end
    I = (1:n) + (n-1)*n
    Vp[I] = A*V[I] + B*V[I-n]
    V .= Vp # Copia sem gastar memória
end
U = reshape(V, n, n)
p2 = surface(x, y, U)
zlims!(p2, 0, 1)
plot(p1, p2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#00002d; stroke-width:1; stroke-opacity:1; fill:none" points="
 15.0633,173.125 14.3864,172.922 14.1608,173.54 14.1608,174.363 14.3864,175.391 14.8376,176.211 15.7401,177.442 16.417,178.468 16.8683,179.7 17.0939,180.728 
 17.0939,181.962 16.8683,182.58 16.6427,182.787 15.9658,182.584 15.0633,181.765 14.3864,180.739 14.1608,180.123 13.9351,179.095 13.9351,177.861 14.1608,177.243 
 14.612,176.83 15.2889,177.032 16.1914,177.44 16.6427,177.438 16.8683,176.82 16.8683,175.997 16.6427,174.969 15.9658,173.944 15.0633,173.125 
 "/>
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 20.6144,280.877 21.7148,279.187 21.7148,266.684 21.1646,267.529 21.7148,266.684 21.7148,254.18 20.6144,255.87 21.7148,254.18 
 21.7148,241.677 21.1646,242.522 21.7148,241.677 21.7148,229.173 20.6144,230.863 21.7148,229.173 21.7148,216.67 21.1646,217.515 21.7148,216.67 21.7148,204.166 
 20.6144,205.856 21.7148,204.166 21.7148,191.663 21.1646,192.508 21.7148,191.663 21.7148,179.159 20.6144,180.849 21.7148,179.159 21.7148,166.656 21.1646,167.501 
 21.7148,166.656 21.7148,154.152 20.6144,155.842 21.7148,154.152 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 20.6144,280.877 21.7148,279.187 36.2836,292.408 35.7334,293.253 36.2836,292.408 50.8524,305.628 49.7521,307.318 50.8524,305.628 
 65.4213,318.849 64.8711,319.694 65.4213,318.849 79.9901,332.069 78.8897,333.76 79.9901,332.069 94.5589,345.29 94.0087,346.135 94.5589,345.29 109.128,358.511 
 108.027,360.201 109.128,358.511 123.697,371.731 123.146,372.576 123.697,371.731 138.265,384.952 137.165,386.642 138.265,384.952 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 138.265,384.952 138.265,384.952 140.596,387.067 138.265,384.952 150.49,366.175 151.656,367.233 150.49,366.175 162.715,347.398 165.046,349.513 162.715,347.398 
 174.94,328.621 176.105,329.679 174.94,328.621 187.164,309.844 189.495,311.96 187.164,309.844 199.389,291.067 200.554,292.125 199.389,291.067 211.614,272.29 
 213.945,274.406 211.614,272.29 223.838,253.514 225.004,254.571 223.838,253.514 236.063,234.737 238.394,236.852 236.063,234.737 
 "/>
 
<image width="214" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAANYAAAF9CAYAAAB4T5a3AAAgAElEQVR4nO29Tahu3ZYe9Iy53nef
fc757lc3ud4QUxUL1EqgUhEtFQ1lCBIQqmVDMIH07MSGxo4g/vRsFAbRjigKsRkCsWnHjiAJKAiC
UnaMqDHYsCxNqr57v59z9prDxvifa71773POXvvnnDk2737Xu/5/5jPHM5455lzEzJg2bdrDWnvq
E5g27XO0Caxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp
0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6w
Caxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp
0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6w
Caxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp
0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6w
Caxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp
0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6w
Caxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp
0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6w
Caxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp
0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6w
Caxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCaxp0w6wCawX
ZD//7t/jn3/7W/zU5zHtbiPm+ZyegxGdmfk9jfN//t1f5vP5awALiBYAHcyMdf0Off0W/fvfxY/+
4L+/2W7a09rpqU

In [153]:
n = 100
U = zeros(n, n)
for i = 1:n
    for j = 1:n
        U[i,j] = f(x[i], y[j])
    end
end
V = U[:]
α = 0.1
A = spdiagm( (α*ones(n-1), (1 - 4α)*ones(n), α*ones(n-1)), (-1,0,1))
B = α*speye(n)
Vp = zeros(n*n)

anim = Animation()
surface(x, y, U)
zlims!(0, 1)
frame(anim)

M = 2000
interval = 50
for k = 1:M
    I = 1:n
    Vp[I] = A*V[I] + B*V[I+n]
    for i = 2:n-1
        I = (1:n) + (i-1)*n
        Vp[I] = B*V[I-n] + A*V[I] + B*V[I+n]
    end
    I = (1:n) + (n-1)*n
    Vp[I] = A*V[I] + B*V[I-n]
    V .= Vp # Copia sem gastar memória
    if k % interval == 0
        U = reshape(V, n, n)
        surface(x, y, U)
        zlims!(0, 1)
        frame(anim)
    end
end

gif(anim, "exemplo_mdf.gif", fps=12)

INFO: Saved animation to /home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo_mdf.gif


Plots.AnimatedGif("/home/abel/projetos/abel/apresentacoes/smne-2016-julia/exemplo_mdf.gif")

## Exercícios

- Faça um gráfico de $f(x) = x^2 - 5x + 6$.
- Faça um gráfico de $f(x) = 2*sin(x)*cos(x)$.
- Faça um gráfico da função $f(x) = 1/x^2$, limitando a visão ao conjunto $[-2,2]\times[-2,2]$.
- Faça uma animação de pontos aparecendo na tela, um de cada vez.
- Faça uma função que recebe $n$ e desenho um circunferência de raio 1, e dois polígonos regulares de $n$ lados.
Um que circunscreve e outro que inscreve a circunferência. 